default:
  data:
    gene_data_path: !expr here::here("data", "gene_data.xlsx")
    animal_data_path: !expr here::here("data", "animal_data.xlsx")
    gene_families_path: !expr here::here("data", "gene_families.xlsx")
    HK_path: !expr here::here("data", "HK_gene_data.xlsx")
    calibration_path: !expr here::here("data", "calibration.xlsx")
    PCR:
      Diff_P4_path: !expr here::here("data", "PCR", "Diff_P4.xlsx")
      Diff_P8_path: !expr here::here("data", "PCR", "Diff_P8.xlsx")
      Diff_P12_path: !expr here::here("data", "PCR", "Diff_P12.xlsx")
      Diff_P21_path: !expr here::here("data", "PCR", "Diff_P21.xlsx")
      Diff_P70_path: !expr here::here("data", "PCR", "Diff_P70.xlsx")
      OS_PC_path: !expr here::here("data", "PCR", "OS_PC.xlsx")
      OS_Tot_path: !expr here::here("data", "PCR", "OS_Tot.xlsx")
    IHC:
      calb_path: !expr here::here("data", "IHC", "Calb.xlsx")
      casp_path: !expr here::here("data", "IHC", "Casp.xlsx")
