```{r}
source("../../src/setup.R", echo = FALSE)

Diff_fig_path <- "PCR/Diff"
```

<!---------------------------------------------------------->
<!---------------------------------------------------------->
# I. Data:
***

```{r}
diff_paths <- c("Diff_P4_path", "Diff_P8_path", "Diff_P12_path", "Diff_P21_path", "Diff_P70_path")

(diff_data_raw <- load_Diffs(diff_paths, max_cq = 33))
```

<!---------------------------------------------------------->
<!---------------------------------------------------------->
# II. Models:
***

**Fit the chosen model to each Gene:**

```{r}
diff_model_cond <- function(data) {
  contrasts(data$Condition) <- contr.sum
  return(glmmTMB(DCq ~ Condition, family = gaussian("identity"), data = data))
}

(diff_mods_cond <- diff_data_raw 
  |> filter(n() >= 3, .by = c(Stage, Layer, Gene, Condition)) # Checking that there are at least 3 values per Condition
  |> group_by(Stage, Layer, Gene)
  |> filter(n_distinct(Condition) >= 2) # Checking that both conditions are present for each Gene
  |> group_split()
  |> map_dfr(\(d) suppressMessages({summarize(d, mod = list(diff_model_cond(pick(everything()))), .by = c(Stage, Layer, Gene))}), .progress = "Fitting models:")
  |> filter(!has_na_coefs(mod))
  |> ungroup()
)
```

**Extract the contrasts, p.values, and CI:**

```{r}
(diff_data_cond <- diff_mods_cond
 |> group_split(Stage, Layer, Gene)
 |> map_dfr(\(d) 
      mutate(d,
        emmeans(mod[[1]], specs = "Condition", type = "response") |> 
          contrast(method = "pairwise", adjust = "none", infer = TRUE) |> 
          as.data.frame() |> 
          select(Condition.cont = matches("estimate|risk|odds|^ratio|^difference"), Condition.LCB = lower.CL, Condition.UCB = upper.CL, Condition.p = p.value)
      ) |> select(-mod),
      .progress = "Extracting model predictions:"
  )
 |> mutate(across(where(is.character), \(x) na_if(x, "NaN")))
 |> right_join(diff_data_raw, by = join_by(Stage, Layer, Gene))
 |> filter(if_all(matches(".p$"), \(x) !is.na(x)))
 |> add_expression("Condition.p")
)
```

<!---------------------------------------------------------->
<!---------------------------------------------------------->
# III. Plots:
***

**Generate boxplots (with p-values) for every gene, split by Layer & Stage:**

```{r}
diff_data_cond |> 
  group_by(Layer, Stage) |> 
  group_walk(\(d, g) {
    n.genes <- n_distinct(d$Gene)
    max.cols <- 6
    n.cols <- min(n.genes, max.cols)
    n.rows <- ceiling(n.genes / max.cols)
  
    make_boxplot_panel(d, n.cols, n.rows, display_labels = TRUE) |>
    save_png(
      glue("BoxPlots [Condition] - {g$Layer} & {g$Stage}"),
      subfolder = Diff_fig_path, width = 1 + n.cols * 2, height = 1 + n.rows * 4
    )
  }, .keep = TRUE
)
```

**Generate Fold change timelines for each Layer and Pathway:**

```{r fig.width = 7, fig.height = 5}
stage_list2 <- c("P4", "P8", "P8 (EGLo)", "P8 (EGLi)", "P12", "P21", "P70")

void <- (diff_data_cond
  |> filter(any(Condition.p <= alpha), .by = c(Gene, Layer_Family))
  |> filter(!(Layer_Family == "PC" & Stage == "P4")) # ⚠️
  |> mutate(Fold = if_else(Condition.p <= alpha, Fold, NA))
  |> mutate(Stage = case_when(
    Layer %in% c("EGLi", "EGLo") ~ glue("{Stage} ({Layer})") |> as.character(),
    .default = as.character(Stage)
    ) |> factor(levels = stage_list2)
  )
  |> group_by(Layer_Family)
  |> group_walk(
    \(d, g) {
      width <- 2 + n_distinct(d$Stage)
      height <- d |> group_by(Pathway_family) |> group_map(\(d, g) n_distinct(d$Gene) * 0.1 + 1.3) |> flatten_dbl() |> sum() # 1
      make_vertical_fold_timeline(d, facet_rows = "Pathway_family", trans = "log", colors = colors_fold, title = g$Layer_Family[[1]], size_boost = 1.5) |> # 2
        save_png(
          glue("Timeline of Fold Change by [Pathway_family] - {g$Layer_Family[[1]]}"),
          subfolder = Diff_fig_path, width = width, height = height
        )
    }
  )
)
```

**Generate the circlize plot:**

```{r}
make_circlize(diff_data_cond, fig_path = here("fig", "PCR", "Diff", "Circlize.png"))
```

